# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.22.0"

before_all do
  sh 'npm i' #Make sure the all missing node packages are installed;
end

desc "Runs all the tests"
lane :test do
end

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |options|
    sh 'cordova build android --dev --device'
    crashlytics({
      apk_path:'platforms/android/build/outputs/apk/android-debug.apk',
      api_token:options[:api_token],
      build_secret:options[:build_secret]
    })
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh 'cordova build android --release --device'
    supply({
      track:'beta',
      apk:'platforms/android/build/outputs/apk/android-release.apk'
    })
  end
end

platform :ios do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    sh 'cordova build ios --dev --device'
  end

  desc "Deploy a new version to the Play Store"
  lane :deploy do
    sh 'cordova build ios --release --device'
  end
end

after_all do |lane|
end

error do |lane, exception|
end